### ISSUE TITLE
Need to clarify the Installation Instructions

### ISSUE THREAD

**Issue by marpierc** [airavata-courses/TeamAlpha#26]
You split these between the wiki and the readme. You should just use one or the other--> consolidate your instructions.

Your instructions say "User Inputs : Below are the fields expected from users."  I assume this refers to the user_input.properties, but I am not sure.  Please clarify. You have this file in two places, but you really should only put it in src/main/resources so that Maven will pick it up and put it in the war.

I was not sure if I needed to enable SSL on the web server or not, so I didn't. Need to clarify if this is required.

I get the login page after starting the tomcat server and pointing my browser to http://localhost:8080/Airavata_Remote_Job_Runner/login.htm, but I am not able to login with the user "airavata" and the password "aaa" as in your README instructions. I don' t see any errors in the logs to indicate the problem. I confirmed that this user was in the db

marpierc=# SELECT \* from airavata_user;
 id | username |             password             |   role    | enabled 
----+----------+----------------------------------+-----------+---------
  1 | airavata | 47bce5c74f589f4867dbd57e9ca9f808 | ROLE_USER |       1
(1 row)

**Comment by marpierc** [comment]
The error that I am getting in the logs file is 2016-03-10 15:10:27,244 ERROR org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter - An internal error occurred while trying to authenticate the user.
org.springframework.security.authentication.InternalAuthenticationServiceException: PreparedStatementCallback; bad SQL grammar [select username,password, enabled from airavata_user where username=?]; nested exception is org.postgresql.util.PSQLException: ERROR: relation "airavata_user" does not exist
  Position: 40
    at org.springframework.security.authentication.dao.DaoAuthenticationProvider.retrieveUser(DaoAuthenticationProvider.java:125)
    at org.springframework.security.authentication.dao.AbstractUserDetailsAuthenticationProvider.authenticate(AbstractUserDetailsAuthenticationProvider.java:143)

But that table exists: 
marpierc=# \dt
             List of relations
 Schema |     Name      | Type  |  Owner  
--------+---------------+-------+----------
 public | airavata_user | table | postgres
(1 row)
